# Generated by Django 2.2.4 on 2021-04-26 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('los_cursos', '0002_auto_20210426_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='los_cursos.Descripcion'),
        ),
    ]
